---
- id: check-commitsar
  name: Check if commits are compliant
  description: Make sure your commits are compliant with conventional commits
  entry: check-commitsar
  language: python
  types: [text]
  pass_filenames: false
  # stages: [commit, post-commit, pre-push, push, manual]
  always_run: true
  # Argument(s) are optional
  # args: [--dry-run] OR [--dry-run, --ticket-prefix, JIRA-]  OR [--ticket-prefix, JIRA-]
